app:
  name: ERP Aynitech
  version: 2.0.0
  description: Gestion interna de la empresa
  web:
    port: 8080
    paths:
      base: /web/
      src: src/
      dist: dist/
      bundles: bundles/
      template: template.pug
  services:
    api: http://localhost:8081
